### ISSUE TITLE
Message field is required

### ISSUE THREAD

**Issue by usrbowe** [bitrise-steplib/steps-slack-message#36] opened 2018-03-01 01:21 UTC
## Issue
If I leave field `"Text of the message to send."` empty, the Slack step fails with error:
```Apollo Guidance Computer
Error: failed to parse config:
- Message: required variable is not present
```

**Comment by viktorbenei** [comment] 2018-03-02 18:05
Hi @usrbowe ,

The message field was always required as far as I know.

May I ask why you want to set an empty message? I'm not against it at all, just don't see a clear use case for it 🤔

**Comment by usrbowe** [comment] 2018-03-05 09:19
Hi,

so actually the only thing which would be nice, is to add `required` label, as other mandatory fields have.
Currently, I end up with not having anything useful top put there.

This is current notification we have:
![image](https://user-images.githubusercontent.com/5339061/36966892-343ca1cc-2099-11e8-91a6-8e771b9d992c.png)

**Comment by viktorbenei** [comment] 2018-03-05 17:45
So the issue is that even though the input is required, it's not marked as required on the UI/in the workflow editor, right @usrbowe ?

**Closed** 2022-05-19 14:26 UTC
Labels: bug, question
